package com.gnm.interview.sriram

object Constants {

  val ENV_KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"
  val ENV_KAFKA_CLIENT_ID = "KAFKA_CLIENT_ID"

  val ENV_PRODUCER_KAFKA_TOPIC_NAME = "PRODUCER_KAFKA_TOPIC_NAME"
  val ENV_PRODUCER_MESSAGES_PER_SEC = "PRODUCER_MESSAGES_PER_SEC"
  val ENV_PRODUCER_PRICE_VARIANCE = "PRODUCER_PRICE_VARIANCE"
}
