package com.gnm.interview.sriram

object Constants {
  val ENV_KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"

  val ENV_CONSUMER_STARTING_OFFSETS = "CONSUMER_STARTING_OFFSETS"
  val ENV_CONSUMER_KAFKA_TOPIC_NAME = "CONSUMER_KAFKA_TOPIC_NAME"
  val ENV_CONSUMER_TRIGGER_INTERVAL_SECS = "CONSUMER_TRIGGER_INTERVAL_SECS"
}
